// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	MainImage   string  `json:"main_image"`
	StartDate   string  `json:"start_date"`
	EndDate     string  `json:"end_date"`
	Status      string  `json:"status"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	ParkID      string  `json:"park_id"`
	UserID      string  `json:"user_id"`
}

type EventInput struct {
	ID          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	MainImage   string  `json:"main_image"`
	StartDate   string  `json:"start_date"`
	EndDate     string  `json:"end_date"`
	Status      string  `json:"status"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	ParkID      string  `json:"park_id"`
	UserID      string  `json:"user_id"`
}

type EventPartialInput struct {
	ID          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	MainImage   *string `json:"main_image,omitempty"`
	StartDate   *string `json:"start_date,omitempty"`
	EndDate     *string `json:"end_date,omitempty"`
	Status      *string `json:"status,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	ParkID      *string `json:"park_id,omitempty"`
	UserID      *string `json:"user_id,omitempty"`
}

type Feature struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UserID    string  `json:"user_id"`
}

type FeatureInput struct {
	ID        *string `json:"id,omitempty"`
	Name      string  `json:"name"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UserID    string  `json:"user_id"`
}

type FeaturePartialInput struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	Status    *string `json:"status,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UserID    *string `json:"user_id,omitempty"`
}

type Park struct {
	ID               string       `json:"id"`
	Name             string       `json:"name"`
	MainImage        string       `json:"main_image"`
	Phone            *string      `json:"phone,omitempty"`
	Hours            *string      `json:"hours,omitempty"`
	AllowsDogs       bool         `json:"allows_dogs"`
	Links            []*ParkLinks `json:"links,omitempty"`
	Status           string       `json:"status"`
	CreatedAt        *string      `json:"created_at,omitempty"`
	UpdatedAt        *string      `json:"updated_at,omitempty"`
	RecreationAreaID string       `json:"recreation_area_id"`
	UserID           string       `json:"user_id"`
}

type ParkHasFeature struct {
	ID        string  `json:"id"`
	Details   *string `json:"details,omitempty"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	ParkID    string  `json:"park_id"`
	FeatureID string  `json:"feature_id"`
}

type ParkHasFeatureInput struct {
	ID        *string `json:"id,omitempty"`
	Details   *string `json:"details,omitempty"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	ParkID    string  `json:"park_id"`
	FeatureID string  `json:"feature_id"`
}

type ParkHasFeaturePartialInput struct {
	ID        *string `json:"id,omitempty"`
	Details   *string `json:"details,omitempty"`
	Status    *string `json:"status,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	ParkID    *string `json:"park_id,omitempty"`
	FeatureID *string `json:"feature_id,omitempty"`
}

type ParkInput struct {
	ID               *string           `json:"id,omitempty"`
	Name             string            `json:"name"`
	MainImage        string            `json:"main_image"`
	Phone            *string           `json:"phone,omitempty"`
	Hours            *string           `json:"hours,omitempty"`
	AllowsDogs       bool              `json:"allows_dogs"`
	Links            []*ParkLinksInput `json:"links,omitempty"`
	Status           string            `json:"status"`
	CreatedAt        *string           `json:"created_at,omitempty"`
	UpdatedAt        *string           `json:"updated_at,omitempty"`
	RecreationAreaID string            `json:"recreation_area_id"`
	UserID           string            `json:"user_id"`
}

type ParkLinks struct {
	Type string `json:"type"`
	Link string `json:"link"`
}

type ParkLinksInput struct {
	Type string `json:"type"`
	Link string `json:"link"`
}

type ParkLinksPartialInput struct {
	Type *string `json:"type,omitempty"`
	Link *string `json:"link,omitempty"`
}

type ParkPartialInput struct {
	ID               *string           `json:"id,omitempty"`
	Name             *string           `json:"name,omitempty"`
	MainImage        *string           `json:"main_image,omitempty"`
	Phone            *string           `json:"phone,omitempty"`
	Hours            *string           `json:"hours,omitempty"`
	AllowsDogs       *bool             `json:"allows_dogs,omitempty"`
	Links            []*ParkLinksInput `json:"links,omitempty"`
	Status           *string           `json:"status,omitempty"`
	CreatedAt        *string           `json:"created_at,omitempty"`
	UpdatedAt        *string           `json:"updated_at,omitempty"`
	RecreationAreaID *string           `json:"recreation_area_id,omitempty"`
	UserID           *string           `json:"user_id,omitempty"`
}

type RecreationArea struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UserID    string  `json:"user_id"`
}

type RecreationAreaInput struct {
	ID        *string `json:"id,omitempty"`
	Name      string  `json:"name"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UserID    string  `json:"user_id"`
}

type RecreationAreaPartialInput struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	Status    *string `json:"status,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UserID    *string `json:"user_id,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type UserInput struct {
	ID        *string `json:"id,omitempty"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Status    string  `json:"status"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type UserPartialInput struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
	Status    *string `json:"status,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}
